name: Overall Application Testing
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_DATABASE: laravel_starter
                    MYSQL_ROOT_PASSWORD: laravel_starter
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - uses: actions/checkout@v3
              name: ğŸ—‚ Checkout code

            - name: ğŸ§© Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22.x'

            - name: ğŸ“¦ Install PNPM
              run: npm i pnpm -g

            - name: ğŸ—ƒ Cache node_modules directory
              uses: actions/cache@v3
              id: node_modules-cache
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}

            - name: ğŸš€ Install NPM packages
              if: steps.node_modules-cache.outputs.cache-hit != 'true'
              run: pnpm i

            - name: ğŸ— Build frontend with vite
              run: pnpm build

            - name: ğŸ˜ Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: ğŸ—„ Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: ğŸ—ƒ Cache Composer dependencies
              uses: actions/cache@v3
              id: actions-cache
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: ğŸ—‚ Cache PHP dependencies
              uses: actions/cache@v3
              id: vendor-cache
              with:
                  path: vendor
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

            - name: ğŸ“‹ Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"

            - name: ğŸ“¦ Install Composer Dependencies
              # if: steps.vendor-cache.outputs.cache-hit != 'true'
              run: composer install --no-interaction --prefer-dist

            - name: ğŸ”‘ Generate key
              run: php artisan key:generate

            - name: ğŸ”§ Directory Permissions
              run: chmod -R 777 storage bootstrap/cache

            - name: ğŸ”„ Run Migrations
              env:
                  DB_CONNECTION: mysql
                  DB_DATABASE: laravel_starter
                  DB_PORT: 3306
                  DB_USER: root
                  DB_HOST: 127.0.0.1
                  DB_PASSWORD: laravel_starter
              run: php artisan migrate:fresh --seed

            - name: ğŸ§ª Execute tests (Unit and Feature tests) via PHPUnit
              env:
                  DB_CONNECTION: mysql
                  DB_DATABASE: laravel_starter
                  DB_PORT: 3306
                  DB_USER: root
                  DB_HOST: 127.0.0.1
                  DB_PASSWORD: laravel_starter
              run: vendor/bin/phpunit --testdox
